# Generated by Django 6.0.2 on 2026-02-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
